name: CI

on: push
# workflow → job → step → action
# jobは並列、step は逐次実行
jobs:
  build0:
    name: build CHM
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'      
    - name: Run a multi-line script
      run: |
        git clone https://github.com/fronoske/bitclust.git
        cd bitclust
        git clone https://github.com/rurema/doctree.git rubydoc
        bundle install --path=vendor/bundle
        
