name: CI

on: push
# workflow → job → step → action
# jobは並列、step は逐次実行
jobs:
  build0:
    name: build CHM
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'      
    - name: Run a multi-line script
      shell: cmd
      run: |
        git clone https://github.com/fronoske/bitclust.git
        cd bitclust
        git clone https://github.com/rurema/doctree.git rubydoc
        bundle install --path=vendor/bundle
        bundle exec bitclust -d ./db init encoding=utf-8 version=2.7.0
        bundle exec bitclust -d ./db update --stdlibtree=./rubydoc/refm/api/src
        if exist chm ( rmdir /S /Q chm )
        bundle exec bitclust -d ./db chm -o ./chm
        
