name: CI
env:
  TARGET_RUBY_VERSION: 2.7.0
on:
  push:
    paths: '.github/workflows/windowsyml'
# workflow → job → step → action
# jobは並列、step は逐次実行
jobs:
  job1:
    name: build CHM
    runs-on: windows-latest
    steps:
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY.MM.DD
      - name: Checkout this repository
        uses: actions/checkout@v2
      - name: Set up Ruby version
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
      - name: Clone fronoske/bitclust
        run:  git clone https://github.com/fronoske/bitclust.git
      - name: Clone rurema/doctree
        working-directory: bitclust
        run: git clone https://github.com/rurema/doctree.git rubydoc
      - name: Set up bundler
        working-directory: bitclust
        run: bundle install --path=vendor/bundle
      - name: Run bitclust
        working-directory: bitclust
        run: |
          bundle exec bitclust -d ./db init encoding=utf-8 version=${{env.TARGET_RUBY_VERSION}}
          bundle exec bitclust -d ./db update --stdlibtree=./rubydoc/refm/api/src
      - name: Generate source file for CHM
        working-directory: bitclust
        run: bundle exec bitclust -d ./db chm -o ./chm
      - name: Run HTML Help Workshop
        working-directory: hhw
        shell: cmd
        run: |
          hhc.exe ..\bitclust\chm\refm.hhp
          copy /y ..\bitclust\chm\refm.chm ..\dist\ruby-refm.chm
      - name: Commit ruby-refm.chm
        working-directory: dist
        shell: cmd
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add ruby-refm.chm
          git commit ruby-refm.chm -m "update ruby-refm.chm"
          git tag v${{env.TARGET_RUBY_VERSION}}-${{steps.current-time.outputs.formattedTime}}
      - name: Push to github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ruby-refm.chm
          name: v${{env.TARGET_RUBY_VERSION}}-${{steps.current-time.outputs.formattedTime}}
          release_name: v${{env.TARGET_RUBY_VERSION}}-${{steps.current-time.outputs.formattedTime}}
          draft: false
          prerelease: false
          body: |
            target Ruby Manual version: v${{env.TARGET_RUBY_VERSION}}
            build date: ${{steps.current-time.outputs.formattedTime}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
