name: CI

on: push
# workflow → job → step → action
# jobは並列、step は逐次実行
jobs:
  build0:
    name: build CHM
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Ruby version
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'
    - name: Clone fronoske/bitclust
      run:  git clone https://github.com/fronoske/bitclust.git
    - name: Clone rurema/doctree
      working-directory: bitclust
      run: git clone https://github.com/rurema/doctree.git rubydoc
    - name: Set up bundler
      working-directory: bitclust
      run: bundle install --path=vendor/bundle
    - name: Run bitclust
      working-directory: bitclust
      run: |
        bundle exec bitclust -d ./db init encoding=utf-8 version=2.7.0
        bundle exec bitclust -d ./db update --stdlibtree=./rubydoc/refm/api/src
    - name: Generate source file for CHM
      working-directory: bitclust
      run: bundle exec bitclust -d ./db chm -o ./chm
    - name: Run HTML Help Workshop
      working-directory: hhw
      shell: cmd
      run: |
        hhc.exe ..\bitclust\chm\refm.hhp
        mkdir ..\dist
        copy /y ..\bitclust\chm\refm.chm ..\dist\ruby-refm.chm
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ruby-refm
        path: dist
